CREATE DATABASE QuanLyDatPhongKhachSan;

USE QuanLyDatPhongKhachSan;

CREATE TABLE KhachHang
(
	MaKH VARCHAR(10) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL,
	QuocTich NVARCHAR(15) NOT NULL,
	MaCMND VARCHAR(15) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(60) NOT NULL,
	SoDienThoai NVARCHAR(12) NOT NULL
)

CREATE TABLE NhanVien
(
	MaNV VARCHAR(10) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL,
	MaCMND VARCHAR(15) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(60) NOT NULL,
	SoDienThoai NVARCHAR(12) NOT NULL,
	MaDangNhap VARCHAR(10) NOT NULL UNIQUE,
	MatKhau NVARCHAR(20) NOT NULL,
)

CREATE TABLE DichVu
(
	MaDV VARCHAR(10) PRIMARY KEY NOT NULL,
	LoaiDV NVARCHAR(50),
	DonViTinh NVARCHAR(5),
	DonGia MONEY
)

CREATE TABLE Phong
(
	MaPhong VARCHAR(10) PRIMARY KEY NOT NULL,
	LoaiPhong NVARCHAR(10),
	GiaPhong MONEY,
	TinhTrangPhong NVARCHAR(20)
)

CREATE TABLE ThongTinDangKy
(
	MaDangKy VARCHAR(20) NOT NULL PRIMARY KEY,
	MaKH VARCHAR(10) NOT NULL CONSTRAINT FK_MAKH FOREIGN KEY REFERENCES KhachHang(MaKH),
	SoLuongPhong INT,
	NgayDen DATE,
	NgayDi DATE
)

CREATE TABLE ThongTinNhan
(
	MaNhanPhong VARCHAR(20) NOT NULL PRIMARY KEY,
	MaDangKy VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES ThongTinDangKy(MaDangKy),
	NgayNhan DATE NOT NULL,
	GioNhan TIME NOT NULL
)

CREATE TABLE ChiTietNhanPhong
(
	MaNhanPhong VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES ThongTinNhan(MaNhanPhong),
	MaPhong VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES Phong(MaPhong),
	PRIMARY KEY (MaNhanPhong, MaPhong)
)

CREATE TABLE ThongTinTraPhong
(
	MaTraPhong VARCHAR(20) NOT NULL PRIMARY KEY,
	MaNhanPhong VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES ThongTinNhan(MaNhanPhong),
	NgayTra DATE NOT NULL,
	GioTra TIME NOT NULL
)

CREATE TABLE HoaDon
(
	MaHoaDon VARCHAR(10) PRIMARY KEY NOT NULL,
	MaNV VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES NhanVien(MaNV),
	MaTraPhong VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES ThongTinTraPhong(MaTraPhong),
	NgayLapHoaDon DATE,
	TongHoaDon MONEY,
)

CREATE TABLE ChiTietHoaDon
(
	MaHoaDon VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES HoaDon(MaHoaDon),
	MaDichVu VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES DichVu(MaDV),
	SoLuong INT,
	TongTien MONEY,
	PRIMARY KEY (MaHoaDon, MaDichVu)
)